fieldinfo: Disallow bitRange width == 0
A field with width 0 does not actually contain any bits so this does not
make sense.  Raise an error here to prevent later code assuming
a bitRange width > 0 from panicking with cryptic messages.  As an
example, in svd2rust you'd get this:

    thread 'main' panicked at 'attempt to shift right with overflow', svd2rust/src/generate/register.rs:295:20